"use client";

import { motion } from "framer-motion";
import { Download, FileCheck2, ArrowUpRight } from "lucide-react";
import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ScoreRing } from "@/components/common/score-ring";
import { getCompanyById, getStakeholdersByCompany, getPainPointsByCompany } from "@/lib/mock-data";

export function ExecutiveReport({ companyId = "anthropic" }: { companyId?: string }) {
  const company = getCompanyById(companyId);
  const stakeholders = getStakeholdersByCompany(companyId);
  const painPoints = getPainPointsByCompany(companyId);

  function handleDownload() {
    if (!company) return;
    const lines = [
      `EXECUTIVE REPORT — ${company.name}`,
      `Generated by ProspectIQ`,
      "",
      `Trust score: ${company.score}/100`,
      `Industry: ${company.industry} · ${company.employees} employees · ${company.revenue}`,
      "",
      "Key findings:",
      "- Engineering leadership has publicly flagged fragmented tooling as a platform-strategy blocker.",
      "- FY26 infra tooling budget has been approved.",
      "- Recommended motion: lead with a platform-consolidation angle to the CTO.",
      "",
      `Stakeholders mapped (${stakeholders.length}):`,
      ...stakeholders.map((s) => `- ${s.name}, ${s.title} — ${s.influence} (score ${s.score})`),
      "",
      `Pain points (${painPoints.length}):`,
      ...painPoints.map((p) => `- [${p.severity.toUpperCase()}] ${p.title} — ${p.confidence}% confidence`),
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${company.name.replace(/\s+/g, "-").toLowerCase()}-executive-report.txt`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  if (!company) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
    >
      <Card className="overflow-hidden">
        <div className="relative border-b border-white/6 bg-gradient-to-b from-white/[0.04] to-transparent px-5 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="rounded-lg border border-white/10 bg-white/[0.05] p-1.5 text-white/70">
                <FileCheck2 className="h-3.5 w-3.5" />
              </div>
              <span className="text-[11px] uppercase tracking-widest text-white/40">Executive Report</span>
            </div>
            <Badge variant="silver">Ready</Badge>
          </div>
        </div>

        <CardHeader className="flex flex-row items-center justify-between space-y-0 pt-4">
          <CardTitle className="text-base">{company.name}</CardTitle>
          <ScoreRing score={company.score} size={54} label="" />
        </CardHeader>

        <CardContent className="space-y-4">
          <p className="text-[13px] leading-relaxed text-white/55">
            Engineering leadership has publicly flagged fragmented tooling as a
            platform-strategy blocker, and FY26 infra budget has been approved.
            Recommended motion: lead with a platform-consolidation angle to the CTO.
          </p>

          <div className="flex flex-wrap gap-2">
            <Badge variant="danger">Critical pain point</Badge>
            <Badge variant="success">Budget approved</Badge>
            <Badge variant="outline">{stakeholders.length} stakeholders</Badge>
          </div>

          <div className="grid grid-cols-3 gap-2.5 pt-1">
            <ReportStat label="Stakeholders" value={String(stakeholders.length)} />
            <ReportStat label="Pain points" value={String(painPoints.length)} />
            <ReportStat label="Confidence" value={`${company.score}%`} />
          </div>

          <div className="flex items-center gap-2 pt-2">
            <Button size="sm" className="flex-1" onClick={handleDownload}>
              <Download className="h-3.5 w-3.5" />
              Download Report
            </Button>
            <Link href={`/accounts/${company.id}`}>
              <Button size="sm" variant="outline">
                View full account <ArrowUpRight className="h-3.5 w-3.5" />
              </Button>
            </Link>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  );
}

function ReportStat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl border border-white/6 bg-white/[0.02] px-3 py-2.5 text-center">
      <p className="text-sm font-semibold text-white/90 tabular-nums">{value}</p>
      <p className="text-[10px] text-white/35">{label}</p>
    </div>
  );
}
