"""add oauth states

Revision ID: 9a43b609f4f4
Revises: a1e5f0c9d3b2
Create Date: 2026-08-15 22:27:33.391077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a43b609f4f4'
down_revision: Union[str, Sequence[str], None] = 'a1e5f0c9d3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_drafts_id'), table_name='outreach_drafts')
    op.drop_table('outreach_drafts')
    op.drop_index(op.f('ix_oauth_states_expires_at'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_id'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_state'), table_name='oauth_states')
    op.drop_index(op.f('ix_oauth_states_user_id'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.alter_column('analysis_results', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_results', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('oauth_states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code_verifier', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('oauth_states_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_states_pkey'))
    )
    op.create_index(op.f('ix_oauth_states_user_id'), 'oauth_states', ['user_id'], unique=False)
    op.create_index(op.f('ix_oauth_states_state'), 'oauth_states', ['state'], unique=True)
    op.create_index(op.f('ix_oauth_states_id'), 'oauth_states', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_states_expires_at'), 'oauth_states', ['expires_at'], unique=False)
    op.create_table('outreach_drafts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('analysis_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stakeholder_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('channel', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('recommended_send_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('recommended_send_reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meeting_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('meeting_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stakeholder_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('email_mx_domain', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_results.id'], name=op.f('outreach_drafts_analysis_id_fkey')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('outreach_drafts_company_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('outreach_drafts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('outreach_drafts_pkey'))
    )
    op.create_index(op.f('ix_outreach_drafts_id'), 'outreach_drafts', ['id'], unique=False)
    # ### end Alembic commands ###
